let regal_txt = `
Our project is called Regal and it is a simple budgeting tool that allows the user to track expenses and plan their financial goals.  The main functionality of the web application will be to allow the user to track income against expenses.  This information will be stored for the user to modify over time.  The user will also be able to track what expenses they deem superfluous in order to separate necessity from wasteful spending. When the user has a surplus of funds,  the application will allow the user to allocate surplus toward planning savings and investments.  Goals for such surplus will be both user defined, and suggested by the app through a few example savings milestones.  The ability to link a bank account to the app will not be supported due to issues with managing project scope as well as issues with security that we may encounter during development.
We have chosen this project because of our shared interest in personal finance.  We all have a good idea of what we want to see in a budgeting app, and believe in our ability to create something purposeful.  An advantage of this particular project is that the app can also be subdivided into manageable, modular goals.  These goals can be easily modified to suit any time constraints or requirement changes we encounter along the way.  If we have extra time,  we can supplement the content of the app with useful widgets such as a calculator that approximates income tax,  or one which calculates interest generated by consistent contributions to savings.
In creating this application,  standard web development platforms will be utilized.  A front end will be created using HTML, CSS, and JavaScript.   The backend of the app will be managed with scripts utilizing Python, Django, Flask, and SQL for database management.  The abilities of the team are diverse among these tools, so a separation of workflow is starting to become apparent. A management app such as Trello will act as a structure to manage workflow efficiently.
`

let paws_txt = `
Personalized Adaptive Web Systems Lab was established in 2004 with support from National Science Foundation and the School of Information Sciences at the University of Pittsburgh. The goal of the PAWS Lab is development and evaluation of innovative user- and group-adaptive Web-based technologies, systems, and architectures. The Lab currently explores a range of user modeling, adaptation, and personalization technologies. The work of the Lab is supported by NSF and DARPA funding.
`

let metroid_txt = `
A metroidvania with a focus on ranged combat and movement. The weapons and gadgets unlocked compliment the movement system and allows for intricate navigation. Sections of proceduraly generated areas branch predesigned locations for a mix of purposefully designed world design and procedurally generated areas inbetween.
`

let pathfinder_txt = `
PathFinder is an educational web application made sometime during senior year of High School. It was a class project where each student was to create their own game from scratch. In PathFinder, you take control over the main character that is stuck inside a Labirinth where there is no way out. Upon traversing the labirinth, you discover multiple NPC's. Each NPC asks a different question where the player must get all questions correct before being able to escape the labirinth.
`

let rdw_txt = `
Dummy
`


// static/assets/img/...
let projects = [
    {title: "Redirected Walking", text: rdw_txt, img:"card_uio.png", from: "January 2021", to: "April 2021"},
    {title: "Regal Finance", text: regal_txt, img:"card_regal.png"},
    {title: "PAWS Lab", text: paws_txt, img:"card_paws.png", from: "May 2020", to: "December 2020"},
    {title: "Metroidvania", text: metroid_txt, img:"card_metroidvania.png", from: "August 2020", to: "December 2020"},
    {title: "PathFinder", text: pathfinder_txt, img:"PathFinder.jpg", from: "August 2016", to: "May 2017"},
]